Update laptop script to handle arm and intel architecture

diff --git a/mac b/mac
--- a/mac
+++ b/mac
@@ -4,13 +4,37 @@
 # Be prepared to turn your laptop (or desktop, no haters here)
 # into an awesome development machine.
 
+show_help() {
+  echo "Setup your development machine"
+  echo "options:"
+  echo "--help                              Show brief help."
+  echo "--skip-homebrew-update              Skip Homebrew formulaes and casks update."
+  exit 0;
+}
+
+while test $# -gt 0; do
+  case "$1" in
+    (-h|--help)
+        show_help;;
+    (--skip-homebrew-update)
+        SKIP_HOMEBREW_UPDATE="true"
+        shift;;
+    *)
+      show_help;;
+  esac
+done
+
+#
+# Functions
+#
+
 fancy_echo() {
   local fmt="$1"; shift
 
   printf "\n$fmt\n" "$@"
 }
 
-append_to_zshrc() {
+safe_append_to_zshrc() {
   local text="$1" zshrc
   local skip_new_line="${2:-0}"
 
@@ -29,32 +53,6 @@ append_to_zshrc() {
   fi
 }
 
-trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
-
-set -e
-
-if [ ! -d "$HOME/.bin/" ]; then
-  mkdir "$HOME/.bin"
-fi
-
-if [ ! -f "$HOME/.zshrc" ]; then
-  touch "$HOME/.zshrc"
-fi
-
-append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'
-
-HOMEBREW_PREFIX="/usr/local"
-
-if [ -d "$HOMEBREW_PREFIX" ]; then
-  if ! [ -r "$HOMEBREW_PREFIX" ]; then
-    sudo chown -R "$LOGNAME:admin" /usr/local
-  fi
-else
-  sudo mkdir "$HOMEBREW_PREFIX"
-  sudo chflags norestricted "$HOMEBREW_PREFIX"
-  sudo chown -R "$LOGNAME:admin" "$HOMEBREW_PREFIX"
-fi
-
 update_shell() {
   local shell_path;
   shell_path="$(which zsh)"
@@ -67,6 +65,59 @@ update_shell() {
   sudo chsh -s "$shell_path" "$USER"
 }
 
+gem_install_or_update() {
+  if gem list "$1" --installed > /dev/null; then
+    gem update "$@"
+  else
+    gem install "$@"
+    rbenv rehash
+  fi
+}
+
+find_latest_ruby() {
+  rbenv install -l | grep -v - | tail -1 | sed -e 's/^ *//'
+}
+
+brew_package_exists() {
+  brew list "${1}" > /dev/null;
+}
+
+activate_exit_on_error() {
+  set -e
+}
+
+deactivate_exit_on_error() {
+  set +e
+}
+
+#
+# Main
+#
+
+activate_exit_on_error
+
+if [ ! -d "$HOME/.bin/" ]; then
+  mkdir "$HOME/.bin"
+fi
+
+if [ ! -f "$HOME/.zshrc" ]; then
+  touch "$HOME/.zshrc"
+fi
+
+safe_append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'
+
+HOMEBREW_PREFIX=$(brew --prefix)
+
+if [ -d "$HOMEBREW_PREFIX" ]; then
+  if ! [ -r "$HOMEBREW_PREFIX" ]; then
+    sudo chown -R "$LOGNAME:admin" "$HOMEBREW_PREFIX"
+  fi
+else
+  sudo mkdir "$HOMEBREW_PREFIX"
+  sudo chflags norestricted "$HOMEBREW_PREFIX"
+  sudo chown -R "$LOGNAME:admin" "$HOMEBREW_PREFIX"
+fi
+
 case "$SHELL" in
   */zsh)
     if [ "$(which zsh)" != '/usr/local/bin/zsh' ] ; then
@@ -78,25 +129,16 @@ case "$SHELL" in
     ;;
 esac
 
-gem_install_or_update() {
-  if gem list "$1" --installed > /dev/null; then
-    gem update "$@"
-  else
-    gem install "$@"
-    rbenv rehash
-  fi
-}
-
 if ! command -v brew >/dev/null; then
   fancy_echo "Installing Homebrew ..."
     curl -fsS \
       'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
 
-    append_to_zshrc '# recommended by brew doctor'
+    safe_append_to_zshrc '# recommended by brew doctor'
 
-    append_to_zshrc 'export PATH="/usr/local/bin:$PATH"' 1
+    safe_append_to_zshrc 'export PATH="$HOMEBREW_PREFIX/bin:$PATH"' 1
 
-    export PATH="/usr/local/bin:$PATH"
+    export PATH="$HOMEBREW_PREFIX/bin:$PATH"
 fi
 
 if brew list | grep -Fq brew-cask; then
@@ -104,81 +146,119 @@ if brew list | grep -Fq brew-cask; then
   brew uninstall --force brew-cask
 fi
 
-fancy_echo "Updating Homebrew formulae ..."
-brew update --force # https://github.com/Homebrew/brew/issues/1151
-brew bundle --file=- <<EOF
-tap "homebrew/services"
-tap "puma/puma"
+if [ ! $SKIP_HOMEBREW_UPDATE ]; then
+  fancy_echo "Updating Homebrew formulae ..."
+  brew update --force # https://github.com/Homebrew/brew/issues/1151
 
-# Unix
-brew "git"
-brew "openssl"
-brew "the_silver_searcher"
-brew "tmux"
-brew "vim"
-brew "zsh"
-brew "jq"
+  # Unset -e to allow Homebrew dependencies update to fail without exiting
+  deactivate_exit_on_error
 
-# GitHub
-brew "hub"
-brew "gh"
+  brew bundle --file=- <<EOF
+    tap "homebrew/services"
+    tap "puma/puma"
+    tap "hashicorp/tap"
 
-# Image manipulation
-brew "imagemagick"
-brew "optipng" 
-brew "jpegoptim"
-brew "pngquant"
+    # Unix
+    brew "git"
+    brew "openssl@1.1"
+    brew "the_silver_searcher"
+    brew "tmux"
+    brew "vim"
+    brew "zsh"
+    brew "jq"
+    brew "bind"
 
-# Programming languages and package managers
-brew "libyaml" # should come after openssl
-brew "node@14"
-brew "rbenv"
-brew "ruby-build"
-brew "yarn"
-brew "puma-dev"
-brew "git-crypt"
-brew "gnupg"
+    # GitHub
+    brew "hub"
+    brew "gh"
 
-# Tools
-brew "anycable-go"
+    # Image manipulation
+    brew "imagemagick"
+    brew "optipng" 
+    brew "jpegoptim"
+    brew "pngquant"
 
-# Databases
-brew "postgresql@13", restart_service: :changed
-brew "redis", restart_service: :changed
+    # Programming languages and package managers
+    brew "libyaml" # should come after openssl
+    brew "node@14"
+    brew "rbenv"
+    brew "ruby-build"
+    brew "yarn"
+    brew "puma-dev"
+    brew "git-crypt"
+    brew "gnupg"
+
+    # Tools
+    brew "anycable-go"
+
+    # Databases
+    brew "postgresql@13", restart_service: :changed
+    brew "redis", restart_service: :changed
+
+    # AWS
+    brew  "awscli"
+
+    # Terraform
+    brew "hashicorp/tap/terraform"
+
+    # Casks
+    cask "google-chrome"
+    cask "visual-studio-code"
+    cask "slack"
+    cask "iterm2"
+    cask "figma"
+    cask "1password"
+    cask "virtualbox"
 EOF
+  activate_exit_on_error
+fi
 
-if brew list | grep --silent "puma-dev"; then
+if brew_package_exists  "puma-dev"; then
   fancy_echo "Configuring puma-dev..."
   sudo puma-dev -setup
   puma-dev -install -d localhost
 fi
 
-if brew list | grep --silent "postgresql@13"; then
+if brew_package_exists "postgresql@13"; then
   fancy_echo "Symlink postgresql@13 binary to /usr/local/bin..."
   brew unlink postgresql@13
   brew link --force postgresql@13
-  ln -s /usr/local/var/postgres /usr/local/var/postgresql@13
+  ln -fs /usr/local/var/postgres $HOMEBREW_PREFIX/var/postgresql@13
 fi
 
-fancy_echo "Configuring Ruby ..."
-find_latest_ruby() {
-  rbenv install -l | grep -v - | tail -1 | sed -e 's/^ *//'
-}
+ruby_version="2.7.4"
+if ! rbenv versions | grep --silent $ruby_version; then
+  fancy_echo "Configuring Ruby ..."
+  safe_append_to_zshrc 'eval "$(rbenv init - --no-rehash)"' 1
+  eval "$(rbenv init -)"
 
-ruby_version="$(find_latest_ruby)"
-append_to_zshrc 'eval "$(rbenv init - --no-rehash)"' 1
-eval "$(rbenv init -)"
+  if ! rbenv versions | grep -Fq "$ruby_version"; then
+    OPEN_SSL_PREFIX=$(brew --prefix openssl@1.1)
 
-if ! rbenv versions | grep -Fq "$ruby_version"; then
-  RUBY_CONFIGURE_OPTS=--with-openssl-dir=/usr/local/opt/openssl rbenv install -s "$ruby_version"
+    PATH="$OPEN_SSL_PREFIX/bin:$PATH" \
+    LDFLAGS="-L$OPEN_SSL_PREFIX/lib" \
+    CPPFLAGS="-I$OPEN_SSL_PREFIX/include" \
+    PKG_CONFIG_PATH="$OPEN_SSL_PREFIX/lib/pkgconfig" \
+    RUBY_CFLAGS="-Wno-error=implicit-function-declaration" \
+    RUBY_CONFIGURE_OPTS=--with-openssl-dir=$OPEN_SSL_PREFIX \
+    rbenv install -s "$ruby_version"
+  fi
+
+  rbenv global "$ruby_version"
+  rbenv shell "$ruby_version"
+
+  gem_install_or_update 'bundler'
+  number_of_cores=$(sysctl -n hw.ncpu)
+  bundle config --global jobs $((number_of_cores - 1))
+
+  deactivate_exit_on_error
+  timeout 240 gem update --system
+  if  $? != 0; then
+    fancy_echo "The optionnal command 'gem update --system' has timeout."
+  fi
+  activate_exit_on_error
 fi
 
-rbenv global "$ruby_version"
-rbenv shell "$ruby_version"
-gem update --system
-gem_install_or_update 'bundler'
-number_of_cores=$(sysctl -n hw.ncpu)
-bundle config --global jobs $((number_of_cores - 1))
 
 if [ -f "$HOME/.laptop.local" ]; then
   fancy_echo "Running your customizations from ~/.laptop.local ..."
